# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            FLK
tagline:          Why always me?
url:              http://flk.club
paginate:         1
baseurl:          /
author:
  name:           heyuntao
  url:            https://www.facebook.com/profile.php?id=100003543193166
  email:          nkuflk@gmail.com
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
  OurStep: '/ourstep/ourstep.html'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/nkuflk/nkuflk.github.io
